name: gradle and docker

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        env:
          timetag: Mona

      - name: Set current date as env variable
        run: echo ${{ env.timetag }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Delete test case
        run: rm -rf src/test
        
      - name: Build with Gradle
        run: gradle build

      - name: Copy the jar
        run: cp build/libs/semogong-0.0.1-SNAPSHOT.jar target/

      - name: Build docker image
        run: docker build -t wjdqlsdlsp/semogong:${{ env.timetag }} .
        
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
      - name: export images_id
        run: images_id=$(docker images -qa wjdqlsdlsp/semogong:${{ env.timetag }})

      - name: tagging
        run: docker tag $images_id wjdqlsdlsp/semogong:${{ env.timetag }} wjdqlsdlsp/semogong:${{ env.timetag }}
        
      - name: push to hub
        run: docker push wjdqlsdlsp/semogong:${{ env.timetag }}
