name: earth-github-action-test CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
# 참고사항
# push가 일어난 브랜치에 PR이 존재하면, push에 대한 이벤트와 PR에 대한 이벤트 모두 발생합니다.

jobs:
  build: 
    runs-on: ubuntu-latest # 실행 환경 지정

    steps:
      - uses: actions/checkout@v2 # github action 버전 지정(major version)

      - name: Set up JDK 11 # JAVA 버전 지정
        uses: actions/setup-java@v1
        with:
          java-version: 11 

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Delete test case
        run: rm -rf src/test
        
      - name: Build with Gradle
        run: gradle build

      - name: Copy the jar
        run: cp build/libs/semogong-0.0.1-SNAPSHOT.jar target/
      
      - name: export date to tag
        run: export date_tag=(date +%s)
        
      - name: Build docker image
        run: docker build -t wjdqlsdlsp/semogong:$date_tag .
        
      - uses: actions/checkout@v1
      - uses: actions/docker/login@master
        with: # Set the secret as an input
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: export images_id
        run: images_id=$(docker images -qa wjdqlsdlsp/semogong:$date_tag)

      - name: tagging
        run: docker tag $images_id wjdqlsdlsp/semogong:$date_tag
        

      - name: push to hub
        run: docker push wjdqlsdlsp/semogong:$date_tag
      
